# # version: "3"

# # services:
# #     db:
# #         container_name: db   
# #         image: postgres:latest
# #         restart: always
# #         environment:
# #             POSTGRES_DB: test123
# #             POSTGRES_USER: root
# #             POSTGRES_PASSWORD: admin123
# #         ports:
# #             - "5432:5432"
# #         volumes:
# #             - pg_data:/var/lib/postgresql/data
# #     pgadmin:
# #             container_name:  pgadmin_c
# #             image: dpage/pgadmin4
# #             depends_on:
# #             - db
# #             ports:
# #             - "5555:80"
# #             # environment:
# #             # PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
# #             # PGADMIN_DEFAULT_PASSWORD: admin
# #             # restart: unless-stopped

# #     redis:
# #         image: redis:latest
# #         restart: always
# #         ports:
# #             - "6379:6379"
# #     # price_s:
# #     #     container_name: cmc_c
# #     #     build: .
# #     #     ports:
# #     #         - "0.0.0.0:8000:8001"
# #     #     env_file:
# #     #         - ./.env
# #     # # web:
# #     #     build:
# #     #         context: ./
# #     #         dockerfile: Dockerfile
# #     #     volumes:
# #     #         - .:/cmcbackend
# #     #     ports:
# #     #         - "8000:8000"
# #     #     depends_on:
# #     #         - db
# #     #         - redis

# # volumes:
# #     pg_data:


# version: "3"
# services:
#   # PG set up
#   db:
#     image: postgres:latest
#     container_name: pg_container
#     restart: always
#     environment:
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=Admin@123
#     ports:
#       - "5432:5432"
#     volumes:
#       - db:/var/lib/postgresql/data
#   pgadmin:
#     container_name: pgadmin4_container
#     image: dpage/pgadmin4
#     restart: always
#     environment:
#       PGADMIN_DEFAULT_EMAIL: happy@gmail.com
#       PGADMIN_DEFAULT_PASSWORD: root
#     ports:
#       - "5050:80"

# volumes:
#   db:
#     driver: local
#   db-data:
#   mongo-data:

version: "3"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db