# Generated by Django 4.2.3 on 2023-07-06 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmcbackend', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Crytos',
            new_name='Cryptos',
        ),
    ]
