# Generated by Django 4.2.3 on 2023-07-07 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmcbackend', '0003_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='title',
        ),
    ]
