# Generated by Django 4.2.3 on 2023-07-07 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmcbackend', '0005_cryptocurrency_alter_categories_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cryptocurrency',
        ),
        migrations.AlterField(
            model_name='categories',
            name='id',
            field=models.CharField(primary_key=True, serialize=False),
        ),
    ]
