# Generated by Django 4.2.3 on 2023-07-07 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmcbackend', '0007_remove_categories_credit_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='market_cap',
            field=models.DecimalField(decimal_places=20, max_digits=50),
        ),
        migrations.AlterField(
            model_name='categories',
            name='volume',
            field=models.DecimalField(decimal_places=20, max_digits=50),
        ),
    ]
