# Generated by Django 4.2.3 on 2023-07-12 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmcbackend', '0008_alter_categories_market_cap_alter_categories_volume'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cryptocurrency',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('symbol', models.CharField(max_length=10)),
                ('slug', models.CharField(max_length=255)),
                ('cmc_rank', models.PositiveIntegerField()),
                ('num_market_pairs', models.PositiveIntegerField()),
                ('circulating_supply', models.BigIntegerField()),
                ('total_supply', models.BigIntegerField()),
                ('max_supply', models.BigIntegerField(blank=True, null=True)),
                ('last_updated', models.DateTimeField()),
                ('date_added', models.DateTimeField()),
                ('tags', models.JSONField(default=list)),
                ('platform', models.CharField(blank=True, max_length=255, null=True)),
                ('usd_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('usd_volume_24h', models.DecimalField(decimal_places=2, max_digits=20)),
                ('usd_percent_change_1h', models.DecimalField(decimal_places=2, max_digits=10)),
                ('usd_percent_change_24h', models.DecimalField(decimal_places=2, max_digits=10)),
                ('usd_percent_change_7d', models.DecimalField(decimal_places=2, max_digits=10)),
                ('usd_market_cap', models.DecimalField(decimal_places=2, max_digits=20)),
                ('usd_last_updated', models.DateTimeField()),
                ('btc_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('btc_volume_24h', models.DecimalField(decimal_places=2, max_digits=20)),
                ('btc_percent_change_1h', models.DecimalField(decimal_places=2, max_digits=10)),
                ('btc_percent_change_24h', models.DecimalField(decimal_places=2, max_digits=10)),
                ('btc_percent_change_7d', models.DecimalField(decimal_places=2, max_digits=10)),
                ('btc_market_cap', models.DecimalField(decimal_places=2, max_digits=20)),
                ('btc_last_updated', models.DateTimeField()),
            ],
        ),
    ]
