# Generated by Django 4.2.3 on 2023-07-12 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmcbackend', '0009_cryptocurrency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryptocurrency',
            name='btc_last_updated',
        ),
        migrations.RemoveField(
            model_name='cryptocurrency',
            name='btc_market_cap',
        ),
        migrations.RemoveField(
            model_name='cryptocurrency',
            name='btc_percent_change_1h',
        ),
        migrations.RemoveField(
            model_name='cryptocurrency',
            name='btc_percent_change_24h',
        ),
        migrations.RemoveField(
            model_name='cryptocurrency',
            name='btc_percent_change_7d',
        ),
        migrations.RemoveField(
            model_name='cryptocurrency',
            name='btc_price',
        ),
        migrations.RemoveField(
            model_name='cryptocurrency',
            name='btc_volume_24h',
        ),
        migrations.RemoveField(
            model_name='cryptocurrency',
            name='usd_last_updated',
        ),
        migrations.RemoveField(
            model_name='cryptocurrency',
            name='usd_market_cap',
        ),
        migrations.RemoveField(
            model_name='cryptocurrency',
            name='usd_percent_change_1h',
        ),
        migrations.RemoveField(
            model_name='cryptocurrency',
            name='usd_percent_change_24h',
        ),
        migrations.RemoveField(
            model_name='cryptocurrency',
            name='usd_percent_change_7d',
        ),
        migrations.RemoveField(
            model_name='cryptocurrency',
            name='usd_price',
        ),
        migrations.RemoveField(
            model_name='cryptocurrency',
            name='usd_volume_24h',
        ),
    ]
