# Generated by Django 4.2.3 on 2023-07-13 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmcbackend', '0010_remove_cryptocurrency_btc_last_updated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listings',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=10)),
                ('last_updated', models.DateTimeField()),
                ('date_added', models.DateTimeField()),
                ('usd_price', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
    ]
