# Generated by Django 4.2.3 on 2023-07-13 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmcbackend', '0013_alter_listings_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='price',
            field=models.DecimalField(decimal_places=20, max_digits=30),
        ),
    ]
