# Generated by Django 4.2.3 on 2023-07-13 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmcbackend', '0014_alter_listings_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('value', models.DecimalField(decimal_places=20, max_digits=30)),
            ],
        ),
    ]
