# Generated by Django 4.2.3 on 2023-07-17 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmcbackend', '0016_delete_categories_delete_cryptocurrency_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Listings',
            new_name='CryptoCoins',
        ),
    ]
