# Generated by Django 4.2.3 on 2023-07-17 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmcbackend', '0017_rename_listings_cryptocoins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='value',
            field=models.DecimalField(decimal_places=20, max_digits=30, null=True),
        ),
    ]
