# Generated by Django 4.2.3 on 2023-07-20 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmcbackend', '0020_coinstest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currencytest',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('value', models.DecimalField(decimal_places=20, max_digits=30, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
